# Example build test from link

name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Give access to execute Gradle
      run: chmod +x ./expass1/gradlew

    - name: Test with Gradle
      run: ./gradlew build
      working-directory: ./expass1
